// <auto-generated />
using System;
using HomeSwapAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeSwapAPI.Migrations
{
    [DbContext(typeof(HomeSwapDbContext))]
    [Migration("20251202212321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeSwapAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Électroménager",
                            City = "Sousse",
                            Condition = "Bon",
                            DateCreated = new DateTime(2025, 12, 2, 21, 23, 21, 105, DateTimeKind.Utc).AddTicks(9593),
                            Description = "Bon état, peu utilisée",
                            Price = 420m,
                            Title = "Machine à laver Samsung 7kg",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = "Meuble",
                            City = "Monastir",
                            Condition = "Très bon",
                            DateCreated = new DateTime(2025, 12, 2, 21, 23, 21, 105, DateTimeKind.Utc).AddTicks(9597),
                            Description = "Tissu beige, très confortable",
                            Price = 350m,
                            Title = "Canapé 3 places",
                            UserId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
